### ISSUE TITLE
Keine Verbindung zum Server und auch nicht zum Gateway

### ISSUE THREAD

**Issue by karlo88** [SebastianSchultz/ioBroker.enet#19]
Hi,
ich habe sowohl Gateway als auch Server vor Ort und bekomme es nicht zum laufen. In Version 0.0.4 wird es nur Gelb, aber die Kanäle kommen trotzdem nicht an. In Version 1.x passiert nur folgendes:

2019-10-15 22:17:46.605  - error: Caught by controller[0]: TypeError: Cannot read property 'toLowerCase' of undefined
--
2019-10-15 22:17:46.605  - error: Caught by controller[0]:     at Adapter. (/opt/iobroker/node_modules/iobroker.enet/main.js:95:39)
2019-10-15 22:17:46.605  - error: Caught by controller[0]:     at emitNone (events.js:106:13)
2019-10-15 22:17:46.606  - error: Caught by controller[0]:     at Adapter.emit (events.js:208:7)
2019-10-15 22:17:46.606  - error: Caught by controller[0]:     at initAdapter (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:4986:18)
2019-10-15 22:17:46.606  - error: Caught by controller[0]:     at /opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:788:29
2019-10-15 22:17:46.606  - error:  Caught by controller[0]:     at Immediate.createInstancesObjects [as  _onImmediate]  (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:748:13)
2019-10-15 22:17:46.606  - error: Caught by controller[0]:     at runCallback (timers.js:798:20)
2019-10-15 22:17:46.606  - error: Caught by controller[0]:     at tryOnImmediate (timers.js:752:5)
2019-10-15 22:17:46.607  - error: Caught by controller[0]:     at processImmediate [as _immediateCallback] (timers.js:729:5)
2019-10-15 22:17:46.607  - error: Caught by controller[1]: TypeError: Cannot read property 'toLowerCase' of undefined
2019-10-15 22:17:46.607  - error: Caught by controller[1]:     at Adapter. (/opt/iobroker/node_modules/iobroker.enet/main.js:95:39)
2019-10-15 22:17:46.607  - error: Caught by controller[1]:     at emitNone (events.js:106:13)
2019-10-15 22:17:46.607  - error: Caught by controller[1]:     at Adapter.emit (events.js:208:7)
2019-10-15 22:17:46.607  - error: Caught by controller[1]:     at initAdapter (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:4986:18)
2019-10-15 22:17:46.607  - error: Caught by controller[1]:     at /opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:788:29
2019-10-15 22:17:46.608  - error:  Caught by controller[1]:     at Immediate.createInstancesObjects [as  _onImmediate]  (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:748:13)
2019-10-15 22:17:46.608  - error: Caught by controller[1]:     at runCallback (timers.js:798:20)
2019-10-15 22:17:46.608  - error: Caught by controller[1]:     at tryOnImmediate (timers.js:752:5)
2019-10-15 22:17:46.608  - error: Caught by controller[1]:     at processImmediate [as _immediateCallback] (timers.js:729:5)
2019-10-15 22:17:46.608  - error: host.ioBroker-RasPi instance system.adapter.enet.0 terminated with code 0 (OK)
2019-10-15 22:17:46.608  - info: host.ioBroker-RasPi Restart adapter system.adapter.enet.0 because enabled

Meine Kenntnisse reichen hier leider nicht weiter, ich wäre froh wenn mir dabei geholfen wird.

Danke!

**Comment by SebastianSchultz** [comment]
Bitte mal den Adapter komplett deinstallieren (nicht nur die Instanz) und manuell neu von der Github URL installieren.
Habe ich soeben gemacht. Fehler tritt nicht mehr auf.

**Comment by karlo88** [comment]
Hallo, erstmal Vielen Dank. Für das gateway funktioniert es jetzt. Zum enet-Server wird das licht nur gelb. Log sieht wie folgt aus:


enet.1 | 2019-10-17 14:04:41.378 | debug | MAIN SERVER
-- | -- | -- | --
enet.1 | 2019-10-17 14:04:41.376 | debug | INIT SERVER
enet.1 | 2019-10-17 14:04:41.376 | info | Running eNet Adapter Version 1.0.1, Configured eNet Server: 192.168.0.22, Username: admin
enet.1 | 2019-10-17 14:04:41.370 | info | starting. Version 1.0.1 in /opt/iobroker/node_modules/iobroker.enet, node: v8.11.1
enet.1 | 2019-10-17 14:04:41.304 | info | States connected to redis: 127.0.0.1:6379
enet.1 | 2019-10-17 14:04:41.298 | debug | statesDB connected
enet.1 | 2019-10-17 14:04:41.246 | debug | objectDB connected

**Comment by SebastianSchultz** [comment]
Hallo, das ist leider korrekt.
Der eNet Server wird derzeit noch nicht unterstützt, da bin ich gerade noch am entwickeln.

**Comment by karlo88** [comment]
Alles, klar danke dir für die Mühe. Falls du irgendwas zum testen brauchst
stehe ich gerne zur Verfügung, habe u.a. auch Bewegungsmelder im enet.

Am Do., 17. Okt. 2019 um 15:52 Uhr schrieb Sebastian Schultz <
notifications@github.com>:
