### ISSUE TITLE
Fehlermeldungen beim Einschalten des Adapters

### ISSUE THREAD

**Issue by mtoensing** [SebastianSchultz/ioBroker.enet#22]
Hi @SebastianSchultz 

ich habe gerade extra wegen diesem Plugin den iobroker per Docker auf meinem Synology NAS gestartet. Andere Plugins scheinen zu laufen und finden z:b. auch die Hue bridge. Dein Plugin sagt aber folgendes: 

"host.7d4adfde9161 | 2020-07-15 23:06:28.565 | info | Restart adapter system.adapter.enet.0 because enabled
-- | -- | -- | --
host.7d4adfde9161 | 2020-07-15 23:06:28.564 | error | instance system.adapter.enet.0 terminated with code 10 (CANNOT_FIND_ADAPTER_DIR)
host.7d4adfde9161 | 2020-07-15 23:06:26.799 | info | instance system.adapter.enet.0 started with pid 1663
host.7d4adfde9161 | 2020-07-15 23:05:56.785 | info | Restart adapter system.adapter.enet.0 because enabled
host.7d4adfde9161 | 2020-07-15 23:05:56.784 | error | instance system.adapter.enet.0 terminated with code 10 (CANNOT_FIND_ADAPTER_DIR)
ical.0 | 2020-07-15 23:05:56.293 | error | at internal/main/run_main_module.js:17:47
ical.0 | 2020-07-15 23:05:56.293 | error | at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
ical.0 | 2020-07-15 23:05:56.293 | error | at Function.Module._load (internal/modules/cjs/loader.js:879:14)
ical.0 | 2020-07-15 23:05:56.293 | error | at Module.load (internal/modules/cjs/loader.js:986:32)
ical.0 | 2020-07-15 23:05:56.293 | error | at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
ical.0 | 2020-07-15 23:05:56.293 | error | at Module._compile (internal/modules/cjs/loader.js:1138:30)
ical.0 | 2020-07-15 23:05:56.293 | error | at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.enet/main.js:33:5)
ical.0 | 2020-07-15 23:05:56.293 | error | at startAdapter (/opt/iobroker/node_modules/iobroker.enet/main.js:65:15)
ical.0 | 2020-07-15 23:05:56.293 | error | at new Adapter (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:8354:47)
ical.0 | 2020-07-15 23:05:56.293 | error | (1645) TypeError: Cannot read property 'common' of undefined
ical.0 | 2020-07-15 23:05:56.292 | error | (1645) uncaught exception: Cannot read property 'common' of undefined
undefined | 2020-07-15 23:05:56.273 | error | Cannot find: /opt/iobroker/io-package.json
undefined | 2020-07-15 23:05:56.272 | warn | Terminated (CANNOT_FIND_ADAPTER_DIR): Without reason
enet.0 | 2020-07-15 23:05:56.291 | error | at internal/main/run_main_module.js:17:47
enet.0 | 2020-07-15 23:05:56.291 | error | at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
enet.0 | 2020-07-15 23:05:56.291 | error | at Function.Module._load (internal/modules/cjs/loader.js:879:14)
enet.0 | 2020-07-15 23:05:56.291 | error | at Module.load (internal/modules/cjs/loader.js:986:32)
enet.0 | 2020-07-15 23:05:56.291 | error | at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
enet.0 | 2020-07-15 23:05:56.291 | error | at Module._compile (internal/modules/cjs/loader.js:1138:30)
enet.0 | 2020-07-15 23:05:56.291 | error | at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.enet/main.js:33:5)
enet.0 | 2020-07-15 23:05:56.291 | error | at startAdapter (/opt/iobroker/node_modules/iobroker.enet/main.js:65:15)
enet.0 | 2020-07-15 23:05:56.291 | error | at new Adapter (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:8354:47)
enet.0 | 2020-07-15 23:05:56.291 | error | (1645) TypeError: Cannot read property 'common' of undefined
undefined | 2020-07-15 23:05:56.269 | error | Cannot find directory of adapter ical
enet.0 | 2020-07-15 23:05:56.288 | error | (1645) uncaught exception: Cannot read property 'common' of undefined
host.7d4adfde9161 | 2020-07-15 23:05:55.399 | info | instance system.adapter.enet.0 started with pid 1645

"

Woran kann das liegen? 

Ich habe mein Gateway konfiguriert. Ich habe das hier und nutze auch die unten verlinkte App: https://partner.gira.com/en_GB/gebaeudetechnik/systeme/enet/enet-produkte/bediengeraete/enet-mobile-gate.html 

Irgendeine Idee was hier das Problem ist?

**Comment by SebastianSchultz** [comment]
Laut Log wirft hier aber eher der ical-Adapter Fehler oder sehe ich das falsch?

**Comment by mtoensing** [comment]
Ich habe einen komplett neuen docker container aufgesetzt. Egal ob Plex oder hue: Alle adapter laufen sofort. Das mit dem ical verstehe ich auch nicht aber muss etwas mit deinem Code zu tun haben. Ich habe aber nun eifnach den ical adapter installiert. 

Nun sieht es so aus: 

```

info.0 | 2020-07-16 12:12:39.465 | info | (147) Popup news was read...
-- | -- | -- | --
host.7d4adfde9161 | 2020-07-16 12:12:37.638 | info | Restart adapter system.adapter.enet.0 because enabled
host.7d4adfde9161 | 2020-07-16 12:12:37.637 | info | instance system.adapter.enet.0 terminated with code 0 (NO_ERROR)
enet.0 | 2020-07-16 12:12:37.604 | info | (2386) Terminated (NO_ERROR): Without reason
enet.0 | 2020-07-16 12:12:37.604 | info | (2386) terminating
ical.0 | 2020-07-16 12:12:37.125 | info | (2386) Terminated (NO_ERROR): Without reason
ical.0 | 2020-07-16 12:12:37.123 | info | (2386) terminating
ical.0 | 2020-07-16 12:12:37.102 | error | (2386) TypeError: Cannot read property 'toLowerCase' of undefined at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.enet/main.js:95:39) at Adapter.emit (events.js:315:20) at /opt
ical.0 | 2020-07-16 12:12:37.101 | error | (2386) unhandled promise rejection: Cannot read property 'toLowerCase' of undefined
ical.0 | 2020-07-16 12:12:37.101 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
enet.0 | 2020-07-16 12:12:37.100 | error | (2386) TypeError: Cannot read property 'toLowerCase' of undefined at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.enet/main.js:95:39) at Adapter.emit (events.js:315:20) at /opt
enet.0 | 2020-07-16 12:12:37.097 | error | (2386) unhandled promise rejection: Cannot read property 'toLowerCase' of undefined
enet.0 | 2020-07-16 12:12:37.096 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
ical.0 | 2020-07-16 12:12:37.090 | info | (2386) starting. Version 1.7.0 in /opt/iobroker/node_modules/iobroker.ical, node: v12.18.2, js-controller: 3.1.6
enet.0 | 2020-07-16 12:12:36.919 | info | (2386) starting. Version 1.0.1 in /opt/iobroker/node_modules/iobroker.enet, node: v12.18.2, js-controller: 3.1.6
host.7d4adfde9161 | 2020-07-16 12:12:35.648 | info | instance system.adapter.enet.0 started with pid 2386
host.7d4adfde9161 | 2020-07-16 12:12:12.730 | info | instance system.adapter.ical.0 terminated with code 0 (NO_ERROR)
ical.0 | 2020-07-16 12:12:12.212 | info | (2371) Terminated (NO_ERROR): Without reason
ical.0 | 2020-07-16 12:12:06.661 | warn | (2371) Error reading "http://11111.ics": Error: getaddrinfo ENOTFOUND 11111.ics
ical.0 | 2020-07-16 12:12:06.660 | warn | (2371) Error reading from URL "http://11111.ics": address not found!
ical.0 | 2020-07-16 12:12:06.633 | info | (2371) Event "ical.0.events.7.Vacation" created
ical.0 | 2020-07-16 12:12:06.633 | info | (2371) Event "ical.0.events.6.Vacation" created
ical.0 | 2020-07-16 12:12:06.632 | info | (2371) Event "ical.0.events.5.Vacation" created
ical.0 | 2020-07-16 12:12:06.632 | info | (2371) Event "ical.0.events.4.Vacation" created
ical.0 | 2020-07-16 12:12:06.632 | info | (2371) Event "ical.0.events.3.Vacation" created
ical.0 | 2020-07-16 12:12:06.631 | info | (2371) Event "ical.0.events.2.Vacation" created
ical.0 | 2020-07-16 12:12:06.631 | info | (2371) Event "ical.0.events.1.Vacation" created
ical.0 | 2020-07-16 12:12:06.630 | info | (2371) Event "ical.0.events.0.now.Vacation" created
ical.0 | 2020-07-16 12:12:06.623 | info | (2371) Event "ical.0.events.0.today.Vacation" created
ical.0 | 2020-07-16 12:12:06.622 | info | (2371) Event "ical.0.events.0.later.Vacation" created
ical.0 | 2020-07-16 12:12:06.541 | info | (2371) starting. Version 1.7.0 in /opt/iobroker/node_modules/iobroker.ical, node: v12.18.2, js-controller: 3.1.6
host.7d4adfde9161 | 2020-07-16 12:12:05.637 | info | Restart adapter system.adapter.enet.0 because enabled
host.7d4adfde9161 | 2020-07-16 12:12:05.637 | info | instance system.adapter.enet.0 terminated with code 0 (NO_ERROR)
enet.0 | 2020-07-16 12:12:05.574 | info | (2356) Terminated (NO_ERROR): Without reason
enet.0 | 2020-07-16 12:12:05.574 | info | (2356) terminating
host.7d4adfde9161 | 2020-07-16 12:12:05.207 | info | instance system.adapter.ical.0 started with pid 2371
host.7d4adfde9161 | 2020-07-16 12:12:05.198 | info | instance scheduled system.adapter.ical.0 0,30 * * * *
ical.0 | 2020-07-16 12:12:05.122 | info | (2356) Terminated (NO_ERROR): Without reason
ical.0 | 2020-07-16 12:12:05.121 | info | (2356) terminating
enet.0 | 2020-07-16 12:12:05.069 | error | at processTicksAndRejections (internal/process/task_queues.js:97:5)
enet.0 | 2020-07-16 12:12:05.069 | error | at /opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:8148:34
enet.0 | 2020-07-16 12:12:05.069 | error | at Adapter.emit (events.js:315:20)
enet.0 | 2020-07-16 12:12:05.069 | error | at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.enet/main.js:95:39)
enet.0 | 2020-07-16 12:12:05.069 | error | (2356) TypeError: Cannot read property 'toLowerCase' of undefined
enet.0 | 2020-07-16 12:12:05.066 | error | (2356) unhandled promise rejection: Cannot read property 'toLowerCase' of undefined
ical.0 | 2020-07-16 12:12:05.071 | error | at processTicksAndRejections (internal/process/task_queues.js:97:5)
ical.0 | 2020-07-16 12:12:05.071 | error | at /opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:8148:34
ical.0 | 2020-07-16 12:12:05.071 | error | at Adapter.emit (events.js:315:20)
ical.0 | 2020-07-16 12:12:05.071 | error | at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.enet/main.js:95:39)
ical.0 | 2020-07-16 12:12:05.071 | error | (2356) TypeError: Cannot read property 'toLowerCase' of undefined
ical.0 | 2020-07-16 12:12:05.070 | error | (2356) unhandled promise rejection: Cannot read property 'toLowerCase' of undefined
Unhandled | 2020-07-16 12:12:05.070 | error | promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
Unhandled | 2020-07-16 12:12:05.065 | error | promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
ical.0 | 2020-07-16 12:12:05.062 | info | (2356) starting. Version 1.7.0 in /opt/iobroker/node_modules/iobroker.ical, node: v12.18.2, js-controller: 3.1.6
enet.0 | 2020-07-16 12:12:04.704 | info | (2356) starting. Version 1.0.1 in /opt/iobroker/node_modules/iobroker.enet, node: v12.18.2, js-controller: 3.1.6
host.7d4adfde9161 | 2020-07-16 12:12:03.409 | info | instance system.adapter.enet.0 started with pid 2356
host.7d4adfde9161 | 2020-07-16 12:12:02.185 | info | stopInstance system.adapter.ical.0 (force=false, process=false)
host.7d4adfde9161 | 2020-07-16 12:12:02.184 | info | "system.adapter.ical.0" enabled
host.7d4adfde9161 | 2020-07-16 12:11:48.010 | info | Restart adapter system.adapter.enet.0 because enabled

 
```

Was hat dein Modul denn mit dem ical adapeter zu tun? Und das in einem komplett leeren Container wo alles andere läuft?

**Comment by mtoensing** [comment]
Ich habe nun iobroker auf einem Raspberry Pi 4 installiert und nicht per Docker auf dem Synology NAS. Das Ergebnis ist das selber. Alles läuft direkt (hue usw) aber das Script hier zeigt das im log. Und ja, da steht was mit ical aber das muss irgendwas mit dem Script für enet zu tun haben. Sonst kommt diese Meldung nicht. 


```
host.raspberrypi | 2020-07-17 15:05:20.328 | info | Restart adapter system.adapter.enet.0 because enabled
-- | -- | -- | --
host.raspberrypi | 2020-07-17 15:05:20.328 | error | instance system.adapter.enet.0 terminated with code 10 (CANNOT_FIND_ADAPTER_DIR)
host.raspberrypi | 2020-07-17 15:05:18.874 | info | instance system.adapter.enet.0 started with pid 29563
host.raspberrypi | 2020-07-17 15:04:48.847 | info | Restart adapter system.adapter.enet.0 because enabled
host.raspberrypi | 2020-07-17 15:04:48.846 | error | instance system.adapter.enet.0 terminated with code 10 (CANNOT_FIND_ADAPTER_DIR)
ical.0 | 2020-07-17 15:04:48.343 | error | at startup (internal/bootstrap/node.js:283:19)
ical.0 | 2020-07-17 15:04:48.343 | error | at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
ical.0 | 2020-07-17 15:04:48.343 | error | at Function.Module._load (internal/modules/cjs/loader.js:585:3)
ical.0 | 2020-07-17 15:04:48.343 | error | at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
ical.0 | 2020-07-17 15:04:48.343 | error | at Module.load (internal/modules/cjs/loader.js:653:32)
ical.0 | 2020-07-17 15:04:48.343 | error | at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
ical.0 | 2020-07-17 15:04:48.343 | error | at Module._compile (internal/modules/cjs/loader.js:778:30)
ical.0 | 2020-07-17 15:04:48.343 | error | at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.enet/main.js:33:5)
ical.0 | 2020-07-17 15:04:48.343 | error | at startAdapter (/opt/iobroker/node_modules/iobroker.enet/main.js:65:15)
ical.0 | 2020-07-17 15:04:48.343 | error | at new Adapter (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:8354:47)
ical.0 | 2020-07-17 15:04:48.343 | error | (29552) TypeError: Cannot read property 'common' of undefined
ical.0 | 2020-07-17 15:04:48.342 | error | (29552) uncaught exception: Cannot read property 'common' of undefined
undefined | 2020-07-17 15:04:48.335 | error | Cannot find: /opt/iobroker/io-package.json
undefined | 2020-07-17 15:04:48.333 | warn | Terminated (CANNOT_FIND_ADAPTER_DIR): Without reason
enet.0 | 2020-07-17 15:04:48.341 | error | at startup (internal/bootstrap/node.js:283:19)
enet.0 | 2020-07-17 15:04:48.341 | error | at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
enet.0 | 2020-07-17 15:04:48.341 | error | at Function.Module._load (internal/modules/cjs/loader.js:585:3)
enet.0 | 2020-07-17 15:04:48.341 | error | at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
enet.0 | 2020-07-17 15:04:48.341 | error | at Module.load (internal/modules/cjs/loader.js:653:32)
enet.0 | 2020-07-17 15:04:48.341 | error | at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
enet.0 | 2020-07-17 15:04:48.341 | error | at Module._compile (internal/modules/cjs/loader.js:778:30)
enet.0 | 2020-07-17 15:04:48.341 | error | at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.enet/main.js:33:5)
enet.0 | 2020-07-17 15:04:48.341 | error | at startAdapter (/opt/iobroker/node_modules/iobroker.enet/main.js:65:15)
enet.0 | 2020-07-17 15:04:48.341 | error | at new Adapter (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:8354:47)
enet.0 | 2020-07-17 15:04:48.341 | error | (29552) TypeError: Cannot read property 'common' of undefined
undefined | 2020-07-17 15:04:48.331 | error | Cannot find directory of adapter ical
enet.0 | 2020-07-17 15:04:48.338 | error | (29552) uncaught exception: Cannot read property 'common' of undefined


host.raspberrypi | 2020-07-17 15:05:20.328 | info | Restart adapter system.adapter.enet.0 because enabled
-- | -- | -- | --
host.raspberrypi | 2020-07-17 15:05:20.328 | error | instance system.adapter.enet.0 terminated with code 10 (CANNOT_FIND_ADAPTER_DIR)
host.raspberrypi | 2020-07-17 15:05:18.874 | info | instance system.adapter.enet.0 started with pid 29563
host.raspberrypi | 2020-07-17 15:04:48.847 | info | Restart adapter system.adapter.enet.0 because enabled
host.raspberrypi | 2020-07-17 15:04:48.846 | error | instance system.adapter.enet.0 terminated with code 10 (CANNOT_FIND_ADAPTER_DIR)
ical.0 | 2020-07-17 15:04:48.343 | error | at startup (internal/bootstrap/node.js:283:19)
ical.0 | 2020-07-17 15:04:48.343 | error | at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
ical.0 | 2020-07-17 15:04:48.343 | error | at Function.Module._load (internal/modules/cjs/loader.js:585:3)
ical.0 | 2020-07-17 15:04:48.343 | error | at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
ical.0 | 2020-07-17 15:04:48.343 | error | at Module.load (internal/modules/cjs/loader.js:653:32)
ical.0 | 2020-07-17 15:04:48.343 | error | at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
ical.0 | 2020-07-17 15:04:48.343 | error | at Module._compile (internal/modules/cjs/loader.js:778:30)
ical.0 | 2020-07-17 15:04:48.343 | error | at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.enet/main.js:33:5)
ical.0 | 2020-07-17 15:04:48.343 | error | at startAdapter (/opt/iobroker/node_modules/iobroker.enet/main.js:65:15)
ical.0 | 2020-07-17 15:04:48.343 | error | at new Adapter (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:8354:47)
ical.0 | 2020-07-17 15:04:48.343 | error | (29552) TypeError: Cannot read property 'common' of undefined
ical.0 | 2020-07-17 15:04:48.342 | error | (29552) uncaught exception: Cannot read property 'common' of undefined
undefined | 2020-07-17 15:04:48.335 | error | Cannot find: /opt/iobroker/io-package.json
undefined | 2020-07-17 15:04:48.333 | warn | Terminated (CANNOT_FIND_ADAPTER_DIR): Without reason
enet.0 | 2020-07-17 15:04:48.341 | error | at startup (internal/bootstrap/node.js:283:19)
enet.0 | 2020-07-17 15:04:48.341 | error | at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
enet.0 | 2020-07-17 15:04:48.341 | error | at Function.Module._load (internal/modules/cjs/loader.js:585:3)
enet.0 | 2020-07-17 15:04:48.341 | error | at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
enet.0 | 2020-07-17 15:04:48.341 | error | at Module.load (internal/modules/cjs/loader.js:653:32)
enet.0 | 2020-07-17 15:04:48.341 | error | at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
enet.0 | 2020-07-17 15:04:48.341 | error | at Module._compile (internal/modules/cjs/loader.js:778:30)
enet.0 | 2020-07-17 15:04:48.341 | error | at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.enet/main.js:33:5)
enet.0 | 2020-07-17 15:04:48.341 | error | at startAdapter (/opt/iobroker/node_modules/iobroker.enet/main.js:65:15)
enet.0 | 2020-07-17 15:04:48.341 | error | at new Adapter (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:8354:47)
enet.0 | 2020-07-17 15:04:48.341 | error | (29552) TypeError: Cannot read property 'common' of undefined
undefined | 2020-07-17 15:04:48.331 | error | Cannot find directory of adapter ical
enet.0 | 2020-07-17 15:04:48.338 | error | (29552) uncaught exception: Cannot read property 'common' of undefined


```

**Comment by mtoensing** [comment]
Ich habe die Lösung: ICh musste komischerweise das Paket hier manuell über github installieren. Dann geht es. Also bei Adapter "Github" auswählen und dieses repository auswählen. Alles taucht nun auf. Danke! =)

**Comment by mtoensing** [comment]
Ich löse mal auf. Ich habe ioBroker nach dieser Anleitung https://marc.tv/synology-iobroker-node-red-alexa/ im Synology NAS mit Docker laufen. Es hat alles funktioniert mit dem eNet Adapter. Dieser war aber immer rot. Aber funktioniert hat er. 

Das Problem: man muss diese Ports auf Docker-Ebene freigeben, die ich hier https://github.com/SebastianSchultz/ioBroker.enet/blob/master/lib/discover.js im Quelltext gefunden habe: 2906 und 3112.

Dann steht "connected to enet" auch auf true mit Docker. =)
