### ISSUE TITLE
Keine Kommunikation mit eNet-Server Version 2.2.1

### ISSUE THREAD

**Issue by GalliAG** [SebastianSchultz/ioBroker.enet#30]
Hallo,
sorry ich bin hier, sowohl in Github als auch IO-Broker neu unterwegs. Deswegen gleichmal ein GROSSES SORRY, wenn ich nicht alles im richtigen Format und vollem Umfang hier abliefere ;-)

Also, ich möchte in den IO-Broker meinen enet-Server einbinden, der mittlerweile doch einige Komponenten im Haus verwaltet (Schalter, Dimmer, Rollladen, Bewegungsmelder).
Ich hab den enet-Adapter, mit der Version hier (Stand: 17.01.2021) installiert und kann keine Verbindung etablieren, hier das Log:

Aktuell habe ich _nodejs 14.15_ installiert, zuvor eine Version10.??.
Eigentlich wollte ich auf die empfohlene V12 updaten, hab dann aber doch irgendwie die V14 erhalten.

Hoffentlich hilft dir das Log, um neue Erkenntnisse zu bekommen.
Wenn du mehr Input brauchst, ... einfach melden :-)

```
enet.0 | 2021-01-21 11:28:04.492 | info | (1624) Terminated (NO_ERROR): Without reason
-- | -- | -- | --
enet.0 | 2021-01-21 11:28:04.491 | info | (1624) terminating
enet.0 | 2021-01-21 11:28:04.483 | error | (1624) Return from eNet Server: "SyntaxError: Unexpected token , in JSON at position 0". Please try to restart the eNet server, change the connection type (HTTP/HTTPS) and check username/password!
enet.0 | 2021-01-21 11:28:04.479 | error | (1624) Return from eNet Server: "SyntaxError: Unexpected end of JSON input". Please try to restart the eNet server, change the connection type (HTTP/HTTPS) and check username/password!
enet.0 | 2021-01-21 11:28:04.285 | info | (1624) Running eNet Adapter Version 1.0.1, Configured eNet Server: 192.168.0.22, Username: admin on port 80
enet.0 | 2021-01-21 11:28:04.257 | info | (1624) starting. Version 1.0.1 in /opt/iobroker/node_modules/iobroker.enet, node: v14.15.4, js-controller: 3.1.6
enet.0 | 2021-01-21 11:27:32.498 | info | (1609) Terminated (NO_ERROR): Without reason
enet.0 | 2021-01-21 11:27:32.496 | info | (1609) terminating
enet.0 | 2021-01-21 11:27:32.488 | error | (1609) Return from eNet Server: "SyntaxError: Unexpected token , in JSON at position 0". Please try to restart the eNet server, change the connection type (HTTP/HTTPS) and check username/password!
enet.0 | 2021-01-21 11:27:32.482 | error | (1609) Return from eNet Server: "SyntaxError: Unexpected end of JSON input". Please try to restart the eNet server, change the connection type (HTTP/HTTPS) and check username/password!
enet.0 | 2021-01-21 11:27:32.252 | info | (1609) Running eNet Adapter Version 1.0.1, Configured eNet Server: 192.168.0.22, Username: admin on port 80
enet.0 | 2021-01-21 11:27:32.224 | info | (1609) starting. Version 1.0.1 in /opt/iobroker/node_modules/iobroker.enet, node: v14.15.4, js-controller: 3.1.6
enet.0 | 2021-01-21 11:27:01.020 | error | (1594) GetDevices Error: Unknown Device: DVT_WS4BJF50, Device UID: 4817369c-0d18-4fab-9b45-b73a01503149, Body: {"jsonrpc":"2.0","result":{"devices":[{"uid":"4817369c-0d18-4fab-9b45-b73a01503149","type
enet.0 | 2021-01-21 11:27:00.564 | error | (1594) TypeError: Cannot read property 'value' of undefined at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/iobroker.enet/main.js:596:155) at IncomingMessage.emit (events.js:327:22)
enet.0 | 2021-01-21 11:27:00.563 | error | (1594) uncaught exception: Cannot read property 'value' of undefined
enet.0 | 2021-01-21 11:27:00.520 | info | (1594) Terminated (NO_ERROR): Without reason
enet.0 | 2021-01-21 11:27:00.519 | info | (1594) terminating
enet.0 | 2021-01-21 11:27:00.460 | error | (1594) TypeError: Cannot read property 'value' of undefined at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/iobroker.enet/main.js:596:155) at IncomingMessage.emit (events.js:327:22)
enet.0 | 2021-01-21 11:27:00.458 | error | (1594) uncaught exception: Cannot read property 'value' of undefined
enet.0 | 2021-01-21 11:27:00.416 | error | (1594) GetDevices Error: Unknown Device: DVT_SV1M, Device UID: 4817369c-0d18-4fab-9b45-b73a06109c6a, Body: {"jsonrpc":"2.0","result":{"devices":[{"uid":"4817369c-0d18-4fab-9b45-b73a06109c6a","typeID":
enet.0 | 2021-01-21 11:27:00.356 | error | (1594) GetDevices Error: Unknown Device: DVT_BS1BP, Device UID: 4817369c-0d18-4fab-9b45-b73a0650ebf9, Body: {"jsonrpc":"2.0","result":{"devices":[{"uid":"4817369c-0d18-4fab-9b45-b73a0650ebf9","typeID"
enet.0 | 2021-01-21 11:27:00.314 | error | (1594) GetDevices Error: Unknown Device: DVT_SA1Z, Device UID: 4817369c-0d18-4fab-9b45-b73a01701bc9, Body: {"jsonrpc":"2.0","result":{"devices":[{"uid":"4817369c-0d18-4fab-9b45-b73a01701bc9","typeID":
enet.0 | 2021-01-21 11:26:59.198 | info | (1594) Running eNet Adapter Version 1.0.1, Configured eNet Server: 192.168.0.22, Username: admin on port 80
enet.0 | 2021-01-21 11:26:59.169 | info | (1594) starting. Version 1.0.1 in /opt/iobroker/node_modules/iobroker.enet, node: v14.15.4, js-controller: 3.1.6
enet.0 | 2021-01-21 11:26:27.718 | error | (1579) GetDevices Error: Unknown Device: DVT_WS4BJF50, Device UID: 4817369c-0d18-4fab-9b45-b73a00800995, Body: {"jsonrpc":"2.0","result":{"devices":[{"uid":"4817369c-0d18-4fab-9b45-b73a00800995","type
enet.0 | 2021-01-21 11:26:27.562 | error | (1579) GetDevices Error: Unknown Device: DVT_SA1Z, Device UID: 4817369c-0d18-4fab-9b45-b73a01701bc9, Body: {"jsonrpc":"2.0","result":{"devices":[{"uid":"4817369c-0d18-4fab-9b45-b73a01701bc9","typeID":
enet.0 | 2021-01-21 11:26:27.555 | error | (1579) GetDevices Error: Unknown Device: DVT_WS1BJ, Device UID: 4817369c-0d18-4fab-9b45-b73a03204898, Body: {"jsonrpc":"2.0","result":{"devices":[{"uid":"4817369c-0d18-4fab-9b45-b73a03204898","typeID"
enet.0 | 2021-01-21 11:26:27.532 | error | (1579) TypeError: Cannot read property 'value' of undefined at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/iobroker.enet/main.js:596:155) at IncomingMessage.emit (events.js:327:22)
enet.0 | 2021-01-21 11:26:27.531 | error | (1579) uncaught exception: Cannot read property 'value' of undefined
enet.0 | 2021-01-21 11:26:27.491 | error | (1579) TypeError: Cannot read property 'value' of undefined at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/iobroker.enet/main.js:596:155) at IncomingMessage.emit (events.js:327:22)
enet.0 | 2021-01-21 11:26:27.490 | error | (1579) uncaught exception: Cannot read property 'value' of undefined
enet.0 | 2021-01-21 11:26:27.331 | error | (1579) GetDevices Error: Unknown Device: DVT_WS4BJF50, Device UID: 4817369c-0d18-4fab-9b45-b73a00202ee4, Body: {"jsonrpc":"2.0","result":{"devices":[{"uid":"4817369c-0d18-4fab-9b45-b73a00202ee4","type
enet.0 | 2021-01-21 11:26:27.304 | info | (1579) Terminated (NO_ERROR): Without reason
enet.0 | 2021-01-21 11:26:27.302 | info | (1579) terminating
enet.0 | 2021-01-21 11:26:27.291 | error | (1579) TypeError: Cannot read property 'value' of undefined at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/iobroker.enet/main.js:596:155) at IncomingMessage.emit (events.js:327:22)
enet.0 | 2021-01-21 11:26:27.289 | error | (1579) uncaught exception: Cannot read property 'value' of undefined
enet.0 | 2021-01-21 11:26:27.003 | error | (1579) GetDevices Error: Unknown Device: DVT_SV1M, Device UID: 4817369c-0d18-4fab-9b45-b73a06109c6a, Body: {"jsonrpc":"2.0","result":{"devices":[{"uid":"4817369c-0d18-4fab-9b45-b73a06109c6a","typeID":
enet.0 | 2021-01-21 11:26:26.803 | error | (1579) GetDevices Error: Unknown Device: DVT_WS4BJF50, Device UID: 4817369c-0d18-4fab-9b45-b73a01002114, Body: {"jsonrpc":"2.0","result":{"devices":[{"uid":"4817369c-0d18-4fab-9b45-b73a01002114","type
enet.0 | 2021-01-21 11:26:26.613 | error | (1579) GetDevices Error: Unknown Device: DVT_BS1BP, Device UID: 4817369c-0d18-4fab-9b45-b73a0650ebf9, Body: {"jsonrpc":"2.0","result":{"devices":[{"uid":"4817369c-0d18-4fab-9b45-b73a0650ebf9","typeID"
enet.0 | 2021-01-21 11:26:25.243 | info | (1579) Running eNet Adapter Version 1.0.1, Configured eNet Server: 192.168.0.22, Username: admin on port 80
enet.0 | 2021-01-21 11:26:25.215 | info | (1579) starting. Version 1.0.1 in /opt/iobroker/node_modules/iobroker.enet, node: v14.15.4, js-controller: 3.1.6
enet.0 | 2021-01-21 11:25:52.647 | error | (1482) GetDevices Error: Unknown Device: DVT_BS1BP, Device UID: 4817369c-0d18-4fab-9b45-b73a0650ebf9, Body: {"jsonrpc":"2.0","result":{"devices":[{"uid":"4817369c-0d18-4fab-9b45-b73a0650ebf9","typeID"
enet.0 | 2021-01-21 11:25:52.456 | info | (1482) Terminated (NO_ERROR): Without reason
enet.0 | 2021-01-21 11:25:52.455 | info | (1482) terminating
enet.0 | 2021-01-21 11:25:52.436 | error | (1482) TypeError: Cannot read property 'value' of undefined at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/iobroker.enet/main.js:596:155) at IncomingMessage.emit (events.js:327:22)
enet.0 | 2021-01-21 11:25:52.434 | error | (1482) uncaught exception: Cannot read property 'value' of undefined
enet.0 | 2021-01-21 11:25:49.651 | info | (1482) Running eNet Adapter Version 1.0.1, Configured eNet Server: 192.168.0.22, Username: admin on port 80
enet.0 | 2021-01-21 11:25:49.623 | info | (1482) starting. Version 1.0.1 in /opt/iobroker/node_modules/iobroker.enet, node: v14.15.4, js-controller: 3.1.6
```

**Comment by SebastianSchultz** [comment]
Hallo,

Die Implementierung des eNet Servers ist leider noch nicht fertig.

**Comment by groot3105** [comment]
Moin,
schließe mich hier mal stumm an, grade das gleiche Problem.
Schon ein gewisser zeitnahen absehbar :)?

**Comment by 64-Paul** [comment]
Hallo,
ich bin auch neu hier und möchte mich mal für die viele Arbeit beim SchützeSchultz bedanken.
Das Thema eNet im ioBroker ist für mich ein Highlight! Leider habe ich natürlich die gleichen Probleme und freue mich, wenn es neuen Code gibt.

**Comment by stoffel7** [comment]
es gibt eine neue Version, bitte mal testen...

**Comment by SebastianSchultz** [comment]
Und bitte hier ein Feedback abgeben :) Danke!

**Comment by GalliAG** [comment]
Hi,
wenn du mit neu Version die "1.0.52 (2021-03-23)" meinst, was neueres konnte ich nicht finden, dann verwende ich schon seit ein paar Wochen.
Zu dieser Version kann ich sagen, das sie bei mir gut läuft und hab aktuell keine Bugs zu berichten :-)

Das einzige was ich beobachtet habe, aber nicht sagen kann wer die Fehlerquelle ist, ist das manchmal Datenpunkte vom eNet-Server in IOBroker (Objekten) nicht aktualisiert werden.
Wenn das für dich interessant ist, werde ich das genauer eingrenzen !

Ansonsten schon mal ein Dickes Danke an Dich, der eNet-Adapter wertet meine Anwendung hier SEHR auf :-)

**Comment by stoffel7** [comment]
der u.a. Fehler (?) wurde auch schon von einem anderen Anwender gemeldet, ich selbst hab das schon bei mir sporadisch beobachtet,
aber es scheint an eNet-Server zu liegen, es scheint, es werden  nicht alle „change events“ an den Adapter ausgegeben.


Von: GalliAG ***@***.***>
Gesendet: Donnerstag, 6. Mai 2021 12:10
An: SebastianSchultz/ioBroker.enet
Cc: Stefan Bruder; Comment
Betreff: Re: [SebastianSchultz/ioBroker.enet] Keine Kommunikation mit eNet-Server Version 2.2.1 (#30)





** CAUTION - email originated from outside the Schaeffler organization






Hi,
wenn du mit neu Version die "1.0.52 (2021-03-23)" meinst, was neueres konnte ich nicht finden, dann verwende ich schon seit ein paar Wochen.
Zu dieser Version kann ich sagen, das sie bei mir gut läuft und hab aktuell keine Bugs zu berichten :-)

Das einzige was ich beobachtet habe, aber nicht sagen kann wer die Fehlerquelle ist, ist das manchmal Datenpunkte vom eNet-Server in IOBroker (Objekten) nicht aktualisiert werden.
Wenn das für dich interessant ist, werde ich das genauer eingrenzen !

Ansonsten schon mal ein Dickes Danke an Dich, der eNet-Adapter wertet meine Anwendung hier SEHR auf :-)

**Comment by stoffel7** [comment]
siehe hierzu Issue:
https://github.com/SebastianSchultz/ioBroker.enet/issues/32
